.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo3 - Debug ]----------"
	@cd "ejemplo3" && "$(MAKE)" -f  "ejemplo3.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo3 - Debug ]----------"
	@cd "ejemplo3" && "$(MAKE)" -f  "ejemplo3.mk" clean
